# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c24c7124023a817eeeb62ab4e46e1c4bd223806a6a03492bd4044675c05fef8c29127dd581dd4e2e95ba88f42a587dce2d3040a4f1371cab75a60531ade3a373
  TEST_SECRET_KEY: sk_test_E5lvbnrJeCbFsCnsJwK0bVz7
  TEST_PUBLISHABLE_KEY: pk_test_2EGWoFJPE26IJfFuipiFEV1M
test:
  secret_key_base: f5e90c9de59bd6327d59130ed74bdad889d4ba2d51a78f30312ffbb27c4773da104ca063bfd0d3fd8ed33a0200dadf99d92b32b0586e14ac96443bfc6fb653d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
